// <auto-generated />
using System;
using Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContexts))]
    partial class AppDbContextsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ComercioRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Comercios");
                });

            modelBuilder.Entity("Domain.Entities.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("pedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("pedidoId");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionPaquete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdComercio")
                        .HasColumnType("int");

                    b.Property<int?>("IdRepartidor")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalProductos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdComercio");

                    b.HasIndex("IdRepartidor");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Domain.Entities.RepartidorRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdRepartidor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPlaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RepartidorId");

                    b.ToTable("Repartidores");
                });

            modelBuilder.Entity("Domain.Entities.ComercioRef", b =>
                {
                    b.OwnsOne("Domain.Entities.Ubicacion", "UbicacionLocal", b1 =>
                        {
                            b1.Property<int>("ComercioRefId")
                                .HasColumnType("int");

                            b1.Property<string>("DireccionTexto")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Local_Direccion");

                            b1.Property<double>("Latitud")
                                .HasColumnType("float")
                                .HasColumnName("Local_Latitud");

                            b1.Property<double>("Longitud")
                                .HasColumnType("float")
                                .HasColumnName("Local_Longitud");

                            b1.Property<string>("Referencia")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Local_Referencia");

                            b1.HasKey("ComercioRefId");

                            b1.ToTable("Comercios");

                            b1.WithOwner()
                                .HasForeignKey("ComercioRefId");
                        });

                    b.Navigation("UbicacionLocal");
                });

            modelBuilder.Entity("Domain.Entities.DetallePedido", b =>
                {
                    b.HasOne("Domain.Entities.Pedido", "pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("pedidoId");

                    b.Navigation("pedido");
                });

            modelBuilder.Entity("Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Domain.Entities.ComercioRef", "Comercio")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdComercio");

                    b.HasOne("Domain.Entities.RepartidorRef", "Repartidor")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdRepartidor");

                    b.OwnsOne("Domain.Entities.Ubicacion", "UbicacionDestino", b1 =>
                        {
                            b1.Property<int>("PedidoId")
                                .HasColumnType("int");

                            b1.Property<string>("DireccionTexto")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Destino_Direccion");

                            b1.Property<double>("Latitud")
                                .HasColumnType("float")
                                .HasColumnName("Destino_Latitud");

                            b1.Property<double>("Longitud")
                                .HasColumnType("float")
                                .HasColumnName("Destino_Longitud");

                            b1.Property<string>("Referencia")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Destino_Referencia");

                            b1.HasKey("PedidoId");

                            b1.ToTable("Pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.OwnsOne("Domain.Entities.Ubicacion", "UbicacionOrigen", b1 =>
                        {
                            b1.Property<int>("PedidoId")
                                .HasColumnType("int");

                            b1.Property<string>("DireccionTexto")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Origen_Direccion");

                            b1.Property<double>("Latitud")
                                .HasColumnType("float")
                                .HasColumnName("Origen_Latitud");

                            b1.Property<double>("Longitud")
                                .HasColumnType("float")
                                .HasColumnName("Origen_Longitud");

                            b1.Property<string>("Referencia")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Origen_Referencia");

                            b1.HasKey("PedidoId");

                            b1.ToTable("Pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.Navigation("Comercio");

                    b.Navigation("Repartidor");

                    b.Navigation("UbicacionDestino");

                    b.Navigation("UbicacionOrigen");
                });

            modelBuilder.Entity("Domain.Entities.RepartidorRef", b =>
                {
                    b.HasOne("Domain.Entities.RepartidorRef", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("Domain.Entities.ComercioRef", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Domain.Entities.RepartidorRef", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
